name: Tests

on: [push, workflow_dispatch]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install deps
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3-tk
    - run: python3 --version
    - name: Python unittest
      uses: onichandame/python-test-action@0.0.0
      env:
        PYTHONPATH: ./src
